# Generated by Django 4.1.1 on 2022-09-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
